### ISSUE TITLE
SendOrder() 메서드에 빠진 내용들

### ISSUE THREAD

**Issue by fordicus** [sharebook-kr/pykiwoom#3]
[참조] https://wikidocs.net/82381

Q1. SendOrder()를 이용한 매수 혹은 매도를 진행 시,
아래와 같은 Windows Pop-up 오류가 발생합니다.
"KHOpenAPI 계좌비밀번호 입력창을 통해 계좌비밀번호를 입력하십시오. [2126]"

계좌비밀번호를 어딘 가에 저장하고 (보안이슈)
수동 입력이 없이 주문이 들어가는 기능이 필요합니다.

Q2. 일단 wikidocs에는 주문에 따른 결과 리턴에 대한
내용이 빠져있습니다. 앞으로 더 공부해서 살펴보겠습니다.

**Comment by brayden-jo** [comment]
Q1. https://wikidocs.net/126081#_2
